library(magrittr)
library(readr)
library(reshape2)
library(stringr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(rstan)
library(ggmap)
library(ggrepel)

options(mc.cores = parallel::detectCores())
